openapi: 3.0.3
info:
  title: Birthdays API
  description: >-
    An API that allows registration of users and their birthdays, as well as
    retrieving that data.
  version: 1.0.0
servers:
  - url: https
paths:
  /hello/{username}:
    summary: Save, update, or get a specific user
    parameters:
      - in: path
        name: username
        schema:
          type: string
          format: "^[a-zA-Z]+$"
        required: true
        description: Username in alpha only (must only contain letters)
    put:
      description: Save or update an existing user with its details
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - dateOfBirth
              properties:
                dateOfBirth:
                  type: string
                  format: date
        required: true
      responses:
        204:
          description: No content returned from an save/update
        400:
          description: Returned if the username or birthday provided is invalid
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string
        500:
          description: An internal server error has occurred
    get:
      description: Return a given users birthday message
      responses:
        200:
          description: The users birthday message
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    format: "^Hello, [a-zA-Z]+! (Your birthday is in [0-9]+ day\\(s\\)|Happy birthday!)$"
        400:
          description: The username was invalid
        404:
          description: The user was not found
        500:
          description: An internal server error has occurred
