apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: birthdays-api
spec:
  scaleTargetRef:
    kind: Deployment
    name: birthdays-api
    apiVersion: apps/v1
  minReplicas: 3
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
